---
format_version: 10
pipelines:
  node-microservice:
    group: microservices
    materials:
      gitrepo:
        git: https://github.com/julijazubova/ci_course.git
    stages:
      - build:
          jobs:
            build:
              tasks:
               - exec:
                   command: bash
                   arguments:
                    - -c
                    - echo "Building application"

      - deploy-dev:
          jobs:
            build:
              tasks:
               - exec:
                   command: bash
                   arguments:
                    - -c
                    - echo "Deployment to DEV"
      
      - test-dev:
          jobs:
            build:
              tasks:
               - exec:
                   command: bash
                   arguments:
                    - -c
                    - echo "Testing in DEV"
        
        
      - deploy-int:
          jobs:
            build:
              tasks:
               - exec:
                   command: bash
                   arguments:
                    - -c
                    - echo "Deployment to INT"


      - test-int:
          jobs:
            build:
              tasks:
               - exec:
                   command: bash
                   arguments:
                    - -c
                    - echo "Testing in INT"
        

      - deploy-prd:
          jobs:
            build:
              tasks:
               - exec:
                   command: bash
                   arguments:
                    - -c
                    - echo "Deployment to PRD"
        
      - test-prd:
          jobs:
            build:
              tasks:
               - exec:
                   command: bash
                   arguments:
                    - -c
                    - echo "Testing in PRD"
        